name: Metrics

on:
  schedule: [{cron: "0 * * * *"}] # runs every hour
  workflow_dispatch: # allows you to run it manually

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
